### ISSUE TITLE
Make links be obviously links

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-campaigns-signup#9]
![image](https://user-images.githubusercontent.com/24901539/188410908-6febc64e-fc65-496c-bfb9-6204dc13c730.png)

**Comment by squigglybob** [comment]
😆 any thoughts on a better style?
It could be the red, and then hover over goes to grey?

**Comment by corsacca** [comment]
like the links on here? https://pray4movement.org/start-a-prayer-network/
